services:
    devenv:
        container_name: devenv
        platform: linux/amd64
        build:
            context: .
            args:
                - SHELL=${SHELL}
                - WORKDIR=${WORKDIR}
                - DK_USER=${DK_USER}
            network: host
        tty: true
        stdin_open: true
        network_mode: host
        volumes:
            - ../../modules/avatochat-server:${WORKDIR}/code
